@testset "Segregating Sites" begin
    S = [dna"aatcga", dna"aaa", dna"tatcg", dna"catcgac", dna"aatc"]
    @test count_segregating_sites(S) == (2, 3)

    S = [dna"ATAATAAAAAAATAATAAAAAAATAAAAAAAATAAAAAAAA",
         dna"AAAAAAAATAAATAATAAAAAAATAAAAAAAAAAAAAAAAA",
         dna"AAAATAAAAATATAATAAAAAAATATAAAAAAAAAAAAAAA",
         dna"AAAAAAAAAAAATAATAAAAAAATAAATAAATAAAAAAAAA",
         dna"AAAATAAAAAAAATATAAAAAAATAAAAAAAAAAAAAAAAA",
         dna"AAAATAAAAAAAAAATAAAAAAAAAAAAAAAAAAATAAAAA",
         dna"AAAAAATAAAAATAATAAAAAAATAAAAAAAAAAAAAAAAA",
         dna"AAAAAAAAAAAAAAATAAAAAAATAAAAAAAAAAAAAAATA",
         dna"AAAAAAAAAAAAAAAAAAAAAAATAAAAAAAAAAAAAAAAA",
         dna"AAAAAAAAAAAAAAATAAAAAAATAATAAAAAAAAAAAAAA"]

    @test count_segregating_sites(S) == (16, 41)
end
